application: crontest
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /testjob1
  script: _go_app
  login: admin
- url: /testjob2
  script: _go_app
  login: admin